config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :authors
  resources :papers

  

end

app/models/application_record.rb
# By default all new Rails 5 applications will have application_record.rb.
# If you are migrating from Rails 4, then simply create app/models/application_record.rb
# as shown below and change all models to inherit from ApplicationRecord instead of ActiveRecord::Base.
# https://stackoverflow.com/questions/41387706/uninitialized-constant-applicationrecord-error#41388844
# https://blog.bigbinary.com/2015/12/28/application-record-in-rails-5.html
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :last_name, presence: true

  has_and_belongs_to_many :papers

  def name
    first_name + ' ' + last_name
  end
end

app/models/paper.rb
class Paper < ApplicationRecord
  validates :title, presence: true
  validates :venue, presence: true
  validates :year, presence: true
  validates :year, numericality: true

  has_and_belongs_to_many :authors

  scope :year, ->(year) { year_eq(year) if year.present? }

  def self.year_eq(year)
    where("year = ?", year)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_parameters)

    if @author.save
      redirect_to @author
    else
      render 'new'
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_parameters)
      redirect_to @author
    else
      render 'edit'
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to authors_path
  end

  private
    def author_parameters
      params.require(:author).permit(:first_name, :last_name, :homepage)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]

  # GET /papers
  def index
    @papers = Paper.year(params[:year])
  end

  # GET /papers/1
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  def create
    @paper = Paper.new(paper_params)

    if @paper.save
      redirect_to @paper, notice: 'Paper was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /papers/1
  def update
    if @paper.update(paper_params)
      redirect_to @paper, notice: 'Paper was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /papers/1
  def destroy
    @paper.destroy
    redirect_to papers_url, notice: 'Paper was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def paper_params
      params.require(:paper).permit(:title, :venue, :year, :author_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/authors/_author.html.erb
<p>
  <strong>Author</strong>
  <%= author.name %>
</p>

app/views/authors/_form.html.erb
<%= form_with(model: @author, local: true) do |form| %>

  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@author.errors.count, "error") %> prohibited
        this author from being updated:
      </h2>
      <ul>
        <% @author.errors.full_messages.each do |error_message| %>
          <li><%= error_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :first_name %>
    <br>
    <%= form.text_field :first_name %>
  </p>

  <p>
    <%= form.label :last_name %>
    <br>
    <%= form.text_area :last_name %>
  </p>

  <p>
    <%= form.label :homepage %>
    <br>
    <%= form.text_area :homepage %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/authors/edit.html.erb
<h1>Edit the author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>List of all authors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Homepage</th>
    <th colspan="23"></th>
  </tr>

  <% @authors.each do |author| %>
    <tr>
      <td><%= author.name %></td>
      <td><%= link_to nil, author.homepage %>
      <td><%= link_to "Show details", author_path(author) %></td>
      <td><%= link_to "Edit details", edit_author_path(author) %></td>
      <td><%= link_to 'Delete', author_path(author),
                      method: :delete,
                      data: { confirm: 'Are you sure to delete this author?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Create a new author", new_author_path %>

app/views/authors/new.html.erb
<h1>Create a new fancy author!</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<h1>Here are the author's details!</h1>

<p>
  <strong>First name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @author.last_name %>
</p>

<p>
  <strong>Homepage:</strong>
  <%= link_to nil, @author.homepage %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paper Management System</h1>

<%= link_to 'Check out all our authors!', controller: 'authors' %>
<%= link_to 'Check out all our papers!', controller: 'papers' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SWT II Intro Exercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/papers/_form.html.erb
<%= form_with(model: paper, local: true) do |form| %>
  <% if paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
        <% paper.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :venue %>
    <%= form.text_field :venue %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :authors %>
    <%= form.select 'author_ids',
      options_from_collection_for_select(Author.all, :id, :name, @paper.author_ids),
      {},
      multiple: true, size: 10 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Papers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Venue</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <td><%= paper.title %></td>
        <td><%= paper.venue %></td>
        <td><%= paper.year %></td>
        <td><%= link_to 'Show', paper %></td>
        <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
        <td><%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paper', new_paper_path %>

app/views/papers/new.html.erb
<h1>New Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @paper.title %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @paper.venue %>
</p>

<p>
  <strong>Year:</strong>
  <%= @paper.year %>
</p>

<h2>Authors</h2>
<%= render @paper.authors %>

<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>